export const QK = {
  agents: () => ["agents"] as const,
  agentsPage: (page: number, pageSize: number, sort = "") =>
    ["agents", "page", page, pageSize, sort] as const,
  agent: (id: string) => ["agents", id] as const,
  conversations: () => ["conversations"] as const,
  conversation: (id: string) => ["conversations", id] as const,
  history: (id: string) => ["conversations", id, "history"] as const,
  workflows: () => ["workflows"] as const,
  workflow: (n: string) => ["workflows", n] as const,
  workflowScript: (n: string) => ["workflows", n, "script"] as const,
  workflowPrerequisites: (n: string) => ["workflows", n, "prerequisites"] as const,
  builderCatalog: () => ["workflows", "builder", "catalog"] as const,
  executions: () => ["workflow-executions"] as const,
  execution: (id: string) => ["workflow-execution", id] as const,
  tools: () => ["tools"] as const,
  tool: (id: string | number) => ["tools", String(id)] as const,
  toolVersions: (name: string) => ["tools", "versions", name] as const,
  pendingTools: () => ["tools", "pending"] as const,
  ontology: () => ["ontology"] as const,
  ontologyTiers: () => ["ontology", "tiers"] as const,
  ontologyConcepts: (scheme = "") => ["ontology", "concepts", scheme] as const,
  ontologyGraph: (params: Record<string, unknown>) => ["ontology", "graph", params] as const,
  annotations: (t: string, id: string) => ["ontology", "annotations", t, id] as const,
  connectors: () => ["connectors"] as const,
  connector: (id: string) => ["connectors", id] as const,
  connectorTools: (id: string) => ["connectors", id, "tools"] as const,
  connectorCreds: (id: string) => ["connectors", id, "credentials"] as const,
  mcpServers: () => ["mcp-servers"] as const,
  mcpServerTools: (n: string) => ["mcp-servers", n, "tools"] as const,
  remoteServers: () => ["remote-servers"] as const,
  remoteServer: (id: string) => ["remote-servers", id] as const,
  remoteServerProviders: () => ["remote-servers", "providers"] as const,
  remoteServerDeployments: (id: string) => ["remote-servers", id, "deployments"] as const,
  remoteServerWorkflows: (id: string) => ["remote-servers", id, "remote-workflows"] as const,
  remoteDeployment: (id: number) => ["remote-deployments", id] as const,
  workflowRemoteDeployments: (name: string) => ["remote-deployments", "workflow", name] as const,
  health: () => ["health"] as const,
  runs: () => ["runs"] as const,
  libraries: () => ["libraries"] as const,
  libraryDocs: (id: string) => ["libraries", id, "documents"] as const,
  rag: () => ["rag"] as const,
  ontologySchemes: () => ["ontology", "schemes"] as const,
  ontologyUsage: (id: string) => ["ontology", "concepts", id, "usage"] as const,
  annotationsList: (params: Record<string, unknown>) =>
    ["ontology", "annotations", "list", params] as const,
  knowledge: (params: Record<string, unknown>) => ["ontology", "knowledge", params] as const,
  knowledgeSearch: (params: Record<string, unknown>) =>
    ["ontology", "knowledge", "search", params] as const,
  scope: (goal: string) => ["ontology", "scope", goal] as const,
  scopeGraph: (goal: string) => ["ontology", "scope", "graph", goal] as const,
  ragOverview: () => ["rag", "overview"] as const,
  ragStatus: () => ["rag", "status"] as const,
  ragLibraryDocs: (id: string) => ["rag", "libraries", id, "documents"] as const,
  ragLibraryRules: (id: string) => ["rag", "libraries", id, "rules"] as const,
  ragDraft: (id: number) => ["rag", "documents", id, "draft"] as const,
  ragGraph: (params: Record<string, unknown>) => ["rag", "graph", params] as const,
  ragTimelines: (params: Record<string, unknown>) => ["rag", "timeline", params] as const,
  ragTimeline: (id: string) => ["rag", "timeline", id] as const,
  ragOptimizer: () => ["rag", "optimizer"] as const,
  workflowDeploymentManifest: (name: string) => ["workflow-deployment-manifest", name] as const,
  ragUnifiedGraph: (params: Record<string, unknown> = {}) =>
    ["rag", "graph", "unified", params] as const,
  rules: (scope = "all") => ["rules", "list", scope] as const,
  ruleTypes: () => ["rules", "types"] as const,
  ruleCategories: () => ["rules", "categories"] as const,
  agentRules: (id: string) => ["rules", "agent", id] as const,
  agentRuleActivity: (id: string) => ["rules", "agent", id, "activity"] as const,
  workflowRules: (name: string) => ["rules", "workflow", name] as const,
  ruleEvents: (params: Record<string, unknown>) => ["rules", "events", params] as const,
  observabilityStatus: () => ["observability", "status"] as const,
  traces: (params: object) => ["observability", "traces", params] as const,
  trace: (id: string) => ["observability", "trace", id] as const,
  executionTrace: (id: string) => ["observability", "execution", id] as const,
  ruleVerdicts: (params: object) => ["observability", "rules", params] as const,
  tracedWorkflows: () => ["observability", "workflows"] as const,
};
