/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as OntologyRouteImport } from './routes/ontology'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ConnectorsIdRouteImport } from './routes/connectors.$id'
import { Route as LibrariesIndexRouteImport } from './routes/libraries.index'
import { Route as LibrariesIdRouteImport } from './routes/libraries.$id'
import { Route as McpIndexRouteImport } from './routes/mcp.index'
import { Route as McpServerNameRouteImport } from './routes/mcp.$serverName'
import { Route as RemoteServersIndexRouteImport } from './routes/remote-servers.index'
import { Route as RemoteServersIdRouteImport } from './routes/remote-servers.$id'
import { Route as RemoteServersNewRouteImport } from './routes/remote-servers.new'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesIdRouteImport } from './routes/rules.$id'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsIdRouteImport } from './routes/tools.$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsArchivedRouteImport } from './routes/workflows.archived'
import { Route as OntologyLibrariesLibraryIdRouteImport } from './routes/ontology_.libraries.$libraryId'
import { Route as WorkflowsWorkflowNameIndexRouteImport } from './routes/workflows.$workflowName.index'
import { Route as WorkflowsWorkflowNameEditRouteImport } from './routes/workflows.$workflowName.edit'
import { Route as WorkflowsWorkflowNameExecuteRouteImport } from './routes/workflows.$workflowName.execute'
import { Route as WorkflowsActivitiesIndexRouteImport } from './routes/workflows.activities.index'
import { Route as WorkflowsActivitiesIdRouteImport } from './routes/workflows.activities.$id'
import { Route as WorkflowsNewIndexRouteImport } from './routes/workflows.new.index'
import { Route as WorkflowsNewAiRouteImport } from './routes/workflows.new.ai'
import { Route as WorkflowsNewVisualRouteImport } from './routes/workflows.new.visual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const OntologyRoute = OntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIdRoute = ConnectorsIdRouteImport.update({
  id: '/connectors/$id',
  path: '/connectors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesRoute,
} as any)
const LibrariesIdRoute = LibrariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibrariesRoute,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServerNameRoute = McpServerNameRouteImport.update({
  id: '/mcp/$serverName',
  path: '/mcp/$serverName',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteServersIndexRoute = RemoteServersIndexRouteImport.update({
  id: '/remote-servers/',
  path: '/remote-servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteServersIdRoute = RemoteServersIdRouteImport.update({
  id: '/remote-servers/$id',
  path: '/remote-servers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteServersNewRoute = RemoteServersNewRouteImport.update({
  id: '/remote-servers/new',
  path: '/remote-servers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdRoute = RulesIdRouteImport.update({
  id: '/rules/$id',
  path: '/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdRoute = ToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsArchivedRoute = WorkflowsArchivedRouteImport.update({
  id: '/workflows/archived',
  path: '/workflows/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const OntologyLibrariesLibraryIdRoute =
  OntologyLibrariesLibraryIdRouteImport.update({
    id: '/ontology_/libraries/$libraryId',
    path: '/ontology/libraries/$libraryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowNameIndexRoute =
  WorkflowsWorkflowNameIndexRouteImport.update({
    id: '/workflows/$workflowName/',
    path: '/workflows/$workflowName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowNameEditRoute =
  WorkflowsWorkflowNameEditRouteImport.update({
    id: '/workflows/$workflowName/edit',
    path: '/workflows/$workflowName/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowNameExecuteRoute =
  WorkflowsWorkflowNameExecuteRouteImport.update({
    id: '/workflows/$workflowName/execute',
    path: '/workflows/$workflowName/execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsActivitiesIndexRoute =
  WorkflowsActivitiesIndexRouteImport.update({
    id: '/workflows/activities/',
    path: '/workflows/activities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsActivitiesIdRoute = WorkflowsActivitiesIdRouteImport.update({
  id: '/workflows/activities/$id',
  path: '/workflows/activities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewIndexRoute = WorkflowsNewIndexRouteImport.update({
  id: '/workflows/new/',
  path: '/workflows/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewAiRoute = WorkflowsNewAiRouteImport.update({
  id: '/workflows/new/ai',
  path: '/workflows/new/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewVisualRoute = WorkflowsNewVisualRouteImport.update({
  id: '/workflows/new/visual',
  path: '/workflows/new/visual',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/libraries': typeof LibrariesRouteWithChildren
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/remote-servers/new': typeof RemoteServersNewRoute
  '/rules/$id': typeof RulesIdRoute
  '/tools/$id': typeof ToolsIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/remote-servers/': typeof RemoteServersIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/ontology/libraries/$libraryId': typeof OntologyLibrariesLibraryIdRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/activities/$id': typeof WorkflowsActivitiesIdRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName/': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/activities/': typeof WorkflowsActivitiesIndexRoute
  '/workflows/new/': typeof WorkflowsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/remote-servers/new': typeof RemoteServersNewRoute
  '/rules/$id': typeof RulesIdRoute
  '/tools/$id': typeof ToolsIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/agents': typeof AgentsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/mcp': typeof McpIndexRoute
  '/remote-servers': typeof RemoteServersIndexRoute
  '/rules': typeof RulesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/ontology/libraries/$libraryId': typeof OntologyLibrariesLibraryIdRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/activities/$id': typeof WorkflowsActivitiesIdRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/activities': typeof WorkflowsActivitiesIndexRoute
  '/workflows/new': typeof WorkflowsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/libraries': typeof LibrariesRouteWithChildren
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/remote-servers/new': typeof RemoteServersNewRoute
  '/rules/$id': typeof RulesIdRoute
  '/tools/$id': typeof ToolsIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/remote-servers/': typeof RemoteServersIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/ontology_/libraries/$libraryId': typeof OntologyLibrariesLibraryIdRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/activities/$id': typeof WorkflowsActivitiesIdRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName/': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/activities/': typeof WorkflowsActivitiesIndexRoute
  '/workflows/new/': typeof WorkflowsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/libraries'
    | '/ontology'
    | '/playground'
    | '/agents/$id'
    | '/connectors/$id'
    | '/libraries/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/remote-servers/new'
    | '/rules/$id'
    | '/tools/$id'
    | '/workflows/archived'
    | '/agents/'
    | '/connectors/'
    | '/libraries/'
    | '/mcp/'
    | '/remote-servers/'
    | '/rules/'
    | '/tools/'
    | '/workflows/'
    | '/ontology/libraries/$libraryId'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/activities/$id'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName/'
    | '/workflows/activities/'
    | '/workflows/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/ontology'
    | '/playground'
    | '/agents/$id'
    | '/connectors/$id'
    | '/libraries/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/remote-servers/new'
    | '/rules/$id'
    | '/tools/$id'
    | '/workflows/archived'
    | '/agents'
    | '/connectors'
    | '/libraries'
    | '/mcp'
    | '/remote-servers'
    | '/rules'
    | '/tools'
    | '/workflows'
    | '/ontology/libraries/$libraryId'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/activities/$id'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName'
    | '/workflows/activities'
    | '/workflows/new'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/libraries'
    | '/ontology'
    | '/playground'
    | '/agents/$id'
    | '/connectors/$id'
    | '/libraries/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/remote-servers/new'
    | '/rules/$id'
    | '/tools/$id'
    | '/workflows/archived'
    | '/agents/'
    | '/connectors/'
    | '/libraries/'
    | '/mcp/'
    | '/remote-servers/'
    | '/rules/'
    | '/tools/'
    | '/workflows/'
    | '/ontology_/libraries/$libraryId'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/activities/$id'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName/'
    | '/workflows/activities/'
    | '/workflows/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LibrariesRoute: typeof LibrariesRouteWithChildren
  OntologyRoute: typeof OntologyRoute
  PlaygroundRoute: typeof PlaygroundRoute
  AgentsIdRoute: typeof AgentsIdRoute
  ConnectorsIdRoute: typeof ConnectorsIdRoute
  McpServerNameRoute: typeof McpServerNameRoute
  RemoteServersIdRoute: typeof RemoteServersIdRoute
  RemoteServersNewRoute: typeof RemoteServersNewRoute
  RulesIdRoute: typeof RulesIdRoute
  ToolsIdRoute: typeof ToolsIdRoute
  WorkflowsArchivedRoute: typeof WorkflowsArchivedRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  RemoteServersIndexRoute: typeof RemoteServersIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  OntologyLibrariesLibraryIdRoute: typeof OntologyLibrariesLibraryIdRoute
  WorkflowsWorkflowNameEditRoute: typeof WorkflowsWorkflowNameEditRoute
  WorkflowsWorkflowNameExecuteRoute: typeof WorkflowsWorkflowNameExecuteRoute
  WorkflowsActivitiesIdRoute: typeof WorkflowsActivitiesIdRoute
  WorkflowsNewAiRoute: typeof WorkflowsNewAiRoute
  WorkflowsNewVisualRoute: typeof WorkflowsNewVisualRoute
  WorkflowsWorkflowNameIndexRoute: typeof WorkflowsWorkflowNameIndexRoute
  WorkflowsActivitiesIndexRoute: typeof WorkflowsActivitiesIndexRoute
  WorkflowsNewIndexRoute: typeof WorkflowsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontology': {
      id: '/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof OntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$id': {
      id: '/connectors/$id'
      path: '/connectors/$id'
      fullPath: '/connectors/$id'
      preLoaderRoute: typeof ConnectorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/'
      fullPath: '/libraries/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof LibrariesRoute
    }
    '/libraries/$id': {
      id: '/libraries/$id'
      path: '/$id'
      fullPath: '/libraries/$id'
      preLoaderRoute: typeof LibrariesIdRouteImport
      parentRoute: typeof LibrariesRoute
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$serverName': {
      id: '/mcp/$serverName'
      path: '/mcp/$serverName'
      fullPath: '/mcp/$serverName'
      preLoaderRoute: typeof McpServerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-servers/': {
      id: '/remote-servers/'
      path: '/remote-servers'
      fullPath: '/remote-servers/'
      preLoaderRoute: typeof RemoteServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-servers/$id': {
      id: '/remote-servers/$id'
      path: '/remote-servers/$id'
      fullPath: '/remote-servers/$id'
      preLoaderRoute: typeof RemoteServersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-servers/new': {
      id: '/remote-servers/new'
      path: '/remote-servers/new'
      fullPath: '/remote-servers/new'
      preLoaderRoute: typeof RemoteServersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id': {
      id: '/rules/$id'
      path: '/rules/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof RulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id': {
      id: '/tools/$id'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof ToolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/archived': {
      id: '/workflows/archived'
      path: '/workflows/archived'
      fullPath: '/workflows/archived'
      preLoaderRoute: typeof WorkflowsArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontology_/libraries/$libraryId': {
      id: '/ontology_/libraries/$libraryId'
      path: '/ontology/libraries/$libraryId'
      fullPath: '/ontology/libraries/$libraryId'
      preLoaderRoute: typeof OntologyLibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/': {
      id: '/workflows/$workflowName/'
      path: '/workflows/$workflowName'
      fullPath: '/workflows/$workflowName/'
      preLoaderRoute: typeof WorkflowsWorkflowNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/edit': {
      id: '/workflows/$workflowName/edit'
      path: '/workflows/$workflowName/edit'
      fullPath: '/workflows/$workflowName/edit'
      preLoaderRoute: typeof WorkflowsWorkflowNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/execute': {
      id: '/workflows/$workflowName/execute'
      path: '/workflows/$workflowName/execute'
      fullPath: '/workflows/$workflowName/execute'
      preLoaderRoute: typeof WorkflowsWorkflowNameExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/activities/': {
      id: '/workflows/activities/'
      path: '/workflows/activities'
      fullPath: '/workflows/activities/'
      preLoaderRoute: typeof WorkflowsActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/activities/$id': {
      id: '/workflows/activities/$id'
      path: '/workflows/activities/$id'
      fullPath: '/workflows/activities/$id'
      preLoaderRoute: typeof WorkflowsActivitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/': {
      id: '/workflows/new/'
      path: '/workflows/new'
      fullPath: '/workflows/new/'
      preLoaderRoute: typeof WorkflowsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/ai': {
      id: '/workflows/new/ai'
      path: '/workflows/new/ai'
      fullPath: '/workflows/new/ai'
      preLoaderRoute: typeof WorkflowsNewAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/visual': {
      id: '/workflows/new/visual'
      path: '/workflows/new/visual'
      fullPath: '/workflows/new/visual'
      preLoaderRoute: typeof WorkflowsNewVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibrariesRouteChildren {
  LibrariesIdRoute: typeof LibrariesIdRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

const LibrariesRouteChildren: LibrariesRouteChildren = {
  LibrariesIdRoute: LibrariesIdRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
}

const LibrariesRouteWithChildren = LibrariesRoute._addFileChildren(
  LibrariesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LibrariesRoute: LibrariesRouteWithChildren,
  OntologyRoute: OntologyRoute,
  PlaygroundRoute: PlaygroundRoute,
  AgentsIdRoute: AgentsIdRoute,
  ConnectorsIdRoute: ConnectorsIdRoute,
  McpServerNameRoute: McpServerNameRoute,
  RemoteServersIdRoute: RemoteServersIdRoute,
  RemoteServersNewRoute: RemoteServersNewRoute,
  RulesIdRoute: RulesIdRoute,
  ToolsIdRoute: ToolsIdRoute,
  WorkflowsArchivedRoute: WorkflowsArchivedRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  McpIndexRoute: McpIndexRoute,
  RemoteServersIndexRoute: RemoteServersIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  OntologyLibrariesLibraryIdRoute: OntologyLibrariesLibraryIdRoute,
  WorkflowsWorkflowNameEditRoute: WorkflowsWorkflowNameEditRoute,
  WorkflowsWorkflowNameExecuteRoute: WorkflowsWorkflowNameExecuteRoute,
  WorkflowsActivitiesIdRoute: WorkflowsActivitiesIdRoute,
  WorkflowsNewAiRoute: WorkflowsNewAiRoute,
  WorkflowsNewVisualRoute: WorkflowsNewVisualRoute,
  WorkflowsWorkflowNameIndexRoute: WorkflowsWorkflowNameIndexRoute,
  WorkflowsActivitiesIndexRoute: WorkflowsActivitiesIndexRoute,
  WorkflowsNewIndexRoute: WorkflowsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
