/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as OntologyRouteImport } from './routes/ontology'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ConnectorsIdRouteImport } from './routes/connectors.$id'
import { Route as McpIndexRouteImport } from './routes/mcp.index'
import { Route as McpServerNameRouteImport } from './routes/mcp.$serverName'
import { Route as RemoteServersIdRouteImport } from './routes/remote-servers.$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsArchivedRouteImport } from './routes/workflows.archived'
import { Route as WorkflowsExecutionsRouteImport } from './routes/workflows.executions'
import { Route as WorkflowsWorkflowNameIndexRouteImport } from './routes/workflows.$workflowName.index'
import { Route as WorkflowsWorkflowNameEditRouteImport } from './routes/workflows.$workflowName.edit'
import { Route as WorkflowsWorkflowNameExecuteRouteImport } from './routes/workflows.$workflowName.execute'
import { Route as WorkflowsNewIndexRouteImport } from './routes/workflows.new.index'
import { Route as WorkflowsNewAiRouteImport } from './routes/workflows.new.ai'
import { Route as WorkflowsNewVisualRouteImport } from './routes/workflows.new.visual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const OntologyRoute = OntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIdRoute = ConnectorsIdRouteImport.update({
  id: '/connectors/$id',
  path: '/connectors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServerNameRoute = McpServerNameRouteImport.update({
  id: '/mcp/$serverName',
  path: '/mcp/$serverName',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteServersIdRoute = RemoteServersIdRouteImport.update({
  id: '/remote-servers/$id',
  path: '/remote-servers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsArchivedRoute = WorkflowsArchivedRouteImport.update({
  id: '/workflows/archived',
  path: '/workflows/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExecutionsRoute = WorkflowsExecutionsRouteImport.update({
  id: '/workflows/executions',
  path: '/workflows/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowNameIndexRoute =
  WorkflowsWorkflowNameIndexRouteImport.update({
    id: '/workflows/$workflowName/',
    path: '/workflows/$workflowName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowNameEditRoute =
  WorkflowsWorkflowNameEditRouteImport.update({
    id: '/workflows/$workflowName/edit',
    path: '/workflows/$workflowName/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowNameExecuteRoute =
  WorkflowsWorkflowNameExecuteRouteImport.update({
    id: '/workflows/$workflowName/execute',
    path: '/workflows/$workflowName/execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsNewIndexRoute = WorkflowsNewIndexRouteImport.update({
  id: '/workflows/new/',
  path: '/workflows/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewAiRoute = WorkflowsNewAiRouteImport.update({
  id: '/workflows/new/ai',
  path: '/workflows/new/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewVisualRoute = WorkflowsNewVisualRouteImport.update({
  id: '/workflows/new/visual',
  path: '/workflows/new/visual',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/executions': typeof ExecutionsRoute
  '/health': typeof HealthRoute
  '/libraries': typeof LibrariesRoute
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName/': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/new/': typeof WorkflowsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/executions': typeof ExecutionsRoute
  '/health': typeof HealthRoute
  '/libraries': typeof LibrariesRoute
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/agents': typeof AgentsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/mcp': typeof McpIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/new': typeof WorkflowsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/executions': typeof ExecutionsRoute
  '/health': typeof HealthRoute
  '/libraries': typeof LibrariesRoute
  '/ontology': typeof OntologyRoute
  '/playground': typeof PlaygroundRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/connectors/$id': typeof ConnectorsIdRoute
  '/mcp/$serverName': typeof McpServerNameRoute
  '/remote-servers/$id': typeof RemoteServersIdRoute
  '/workflows/archived': typeof WorkflowsArchivedRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$workflowName/edit': typeof WorkflowsWorkflowNameEditRoute
  '/workflows/$workflowName/execute': typeof WorkflowsWorkflowNameExecuteRoute
  '/workflows/new/ai': typeof WorkflowsNewAiRoute
  '/workflows/new/visual': typeof WorkflowsNewVisualRoute
  '/workflows/$workflowName/': typeof WorkflowsWorkflowNameIndexRoute
  '/workflows/new/': typeof WorkflowsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/executions'
    | '/health'
    | '/libraries'
    | '/ontology'
    | '/playground'
    | '/tools'
    | '/agents/$id'
    | '/connectors/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/workflows/archived'
    | '/workflows/executions'
    | '/agents/'
    | '/connectors/'
    | '/mcp/'
    | '/workflows/'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName/'
    | '/workflows/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/executions'
    | '/health'
    | '/libraries'
    | '/ontology'
    | '/playground'
    | '/tools'
    | '/agents/$id'
    | '/connectors/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/workflows/archived'
    | '/workflows/executions'
    | '/agents'
    | '/connectors'
    | '/mcp'
    | '/workflows'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName'
    | '/workflows/new'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/executions'
    | '/health'
    | '/libraries'
    | '/ontology'
    | '/playground'
    | '/tools'
    | '/agents/$id'
    | '/connectors/$id'
    | '/mcp/$serverName'
    | '/remote-servers/$id'
    | '/workflows/archived'
    | '/workflows/executions'
    | '/agents/'
    | '/connectors/'
    | '/mcp/'
    | '/workflows/'
    | '/workflows/$workflowName/edit'
    | '/workflows/$workflowName/execute'
    | '/workflows/new/ai'
    | '/workflows/new/visual'
    | '/workflows/$workflowName/'
    | '/workflows/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  ExecutionsRoute: typeof ExecutionsRoute
  HealthRoute: typeof HealthRoute
  LibrariesRoute: typeof LibrariesRoute
  OntologyRoute: typeof OntologyRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ToolsRoute: typeof ToolsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  ConnectorsIdRoute: typeof ConnectorsIdRoute
  McpServerNameRoute: typeof McpServerNameRoute
  RemoteServersIdRoute: typeof RemoteServersIdRoute
  WorkflowsArchivedRoute: typeof WorkflowsArchivedRoute
  WorkflowsExecutionsRoute: typeof WorkflowsExecutionsRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsWorkflowNameEditRoute: typeof WorkflowsWorkflowNameEditRoute
  WorkflowsWorkflowNameExecuteRoute: typeof WorkflowsWorkflowNameExecuteRoute
  WorkflowsNewAiRoute: typeof WorkflowsNewAiRoute
  WorkflowsNewVisualRoute: typeof WorkflowsNewVisualRoute
  WorkflowsWorkflowNameIndexRoute: typeof WorkflowsWorkflowNameIndexRoute
  WorkflowsNewIndexRoute: typeof WorkflowsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontology': {
      id: '/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof OntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$id': {
      id: '/connectors/$id'
      path: '/connectors/$id'
      fullPath: '/connectors/$id'
      preLoaderRoute: typeof ConnectorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$serverName': {
      id: '/mcp/$serverName'
      path: '/mcp/$serverName'
      fullPath: '/mcp/$serverName'
      preLoaderRoute: typeof McpServerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-servers/$id': {
      id: '/remote-servers/$id'
      path: '/remote-servers/$id'
      fullPath: '/remote-servers/$id'
      preLoaderRoute: typeof RemoteServersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/archived': {
      id: '/workflows/archived'
      path: '/workflows/archived'
      fullPath: '/workflows/archived'
      preLoaderRoute: typeof WorkflowsArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/executions': {
      id: '/workflows/executions'
      path: '/workflows/executions'
      fullPath: '/workflows/executions'
      preLoaderRoute: typeof WorkflowsExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/': {
      id: '/workflows/$workflowName/'
      path: '/workflows/$workflowName'
      fullPath: '/workflows/$workflowName/'
      preLoaderRoute: typeof WorkflowsWorkflowNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/edit': {
      id: '/workflows/$workflowName/edit'
      path: '/workflows/$workflowName/edit'
      fullPath: '/workflows/$workflowName/edit'
      preLoaderRoute: typeof WorkflowsWorkflowNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowName/execute': {
      id: '/workflows/$workflowName/execute'
      path: '/workflows/$workflowName/execute'
      fullPath: '/workflows/$workflowName/execute'
      preLoaderRoute: typeof WorkflowsWorkflowNameExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/': {
      id: '/workflows/new/'
      path: '/workflows/new'
      fullPath: '/workflows/new/'
      preLoaderRoute: typeof WorkflowsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/ai': {
      id: '/workflows/new/ai'
      path: '/workflows/new/ai'
      fullPath: '/workflows/new/ai'
      preLoaderRoute: typeof WorkflowsNewAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new/visual': {
      id: '/workflows/new/visual'
      path: '/workflows/new/visual'
      fullPath: '/workflows/new/visual'
      preLoaderRoute: typeof WorkflowsNewVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  ExecutionsRoute: ExecutionsRoute,
  HealthRoute: HealthRoute,
  LibrariesRoute: LibrariesRoute,
  OntologyRoute: OntologyRoute,
  PlaygroundRoute: PlaygroundRoute,
  ToolsRoute: ToolsRoute,
  AgentsIdRoute: AgentsIdRoute,
  ConnectorsIdRoute: ConnectorsIdRoute,
  McpServerNameRoute: McpServerNameRoute,
  RemoteServersIdRoute: RemoteServersIdRoute,
  WorkflowsArchivedRoute: WorkflowsArchivedRoute,
  WorkflowsExecutionsRoute: WorkflowsExecutionsRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  McpIndexRoute: McpIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsWorkflowNameEditRoute: WorkflowsWorkflowNameEditRoute,
  WorkflowsWorkflowNameExecuteRoute: WorkflowsWorkflowNameExecuteRoute,
  WorkflowsNewAiRoute: WorkflowsNewAiRoute,
  WorkflowsNewVisualRoute: WorkflowsNewVisualRoute,
  WorkflowsWorkflowNameIndexRoute: WorkflowsWorkflowNameIndexRoute,
  WorkflowsNewIndexRoute: WorkflowsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
