"""
Workflow Models — Pydantic schemas and definitions for workflow engine.
Aligned with Mistral Beta Workflows API (v1/workflows).
"""

import json
from pydantic import BaseModel, ConfigDict, Field, computed_field
from typing import Optional, Any
from datetime import datetime
from enum import Enum


class StepType(str, Enum):
    AGENT = "agent"
    TOOL = "tool"
    CONNECTOR = "connector"
    CONDITION = "condition"
    TRANSFORM = "transform"


class WorkflowStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TERMINATED = "TERMINATED"
    TIMED_OUT = "TIMED_OUT"
    CONTINUED_AS_NEW = "CONTINUED_AS_NEW"


class WorkflowSource(str, Enum):
    """How a workflow definition was authored."""
    PLANNER = "planner"   # generated by the LLM workflow planner
    BUILDER = "builder"   # assembled by hand in the visual builder


class NodeLayout(BaseModel):
    """Canvas coordinates for a single step in the visual builder.

    Purely presentational — the execution engine and the compiler ignore it.
    Persisted so a builder-authored graph reopens exactly as the user left it.
    """
    x: float = 0.0
    y: float = 0.0


class WorkflowStep(BaseModel):
    """A single step in the workflow DAG."""
    id: str
    type: StepType
    tier: Optional[str] = None
    config: dict = Field(default_factory=dict)
    # For agent steps: {"agent_id": "...", "query_template": "..."} or {"model": "...", "instructions": "..."}
    # For tool steps: {"tool_name": "...", "arguments_template": {}}
    # For connector steps: {"connector_id": "...", "connector_name": "...",
    #                       "tool_name": "...", "arguments": {}, "credentials_name": "..."}
    # For condition steps: {"expression": "...", "true_step": "...", "false_step": "..."}
    # For transform steps: {"transform_code": "..."}
    next_steps: list[str] = Field(default_factory=list)
    description: Optional[str] = None
    parallel_group: Optional[str] = None  # Steps sharing the same group ID run concurrently via asyncio.gather()


class RuleRef(BaseModel):
    """A workflow rule selected for one workflow (see ``app.rules``).

    Always-on rules apply without being listed; this is the optional ones
    somebody — the planner or a person in the builder — chose, and why.
    """
    rule_id: str
    source: str = "user"      # ai | user
    reason: str = ""


class WorkflowDefinition(BaseModel):
    """Full workflow definition — a DAG of steps.

    This object is the single source of truth for a workflow. The compiled
    Mistral Workflows SDK module is a build artifact derived from it, never
    the other way round.
    """

    # Assignments are validated so server-side mutations (ui_layout from the
    # builder, published_hash on publish) are coerced to the declared types
    # instead of silently storing whatever shape was assigned. Definitions are
    # mutated rarely, so the per-assignment cost is irrelevant here.
    model_config = ConfigDict(validate_assignment=True)

    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    steps: list[WorkflowStep]
    entry_step: str
    input_schema: list[dict] = Field(default_factory=list)
    variables: dict = Field(default_factory=dict)
    is_deployed: bool = False
    archived: bool = False

    # ── Authoring metadata (additive; defaults keep older records loadable) ──
    source: WorkflowSource = WorkflowSource.PLANNER
    ui_layout: dict[str, NodeLayout] = Field(default_factory=dict)
    # SHA-256 of the semantic definition at the last successful publish.
    # Compared against the live hash to derive "has unpublished changes" —
    # stored rather than a boolean flag so it cannot drift out of sync.
    published_hash: Optional[str] = None

    # Optional workflow rules selected for this workflow. They change how it
    # runs, so they are part of the semantic hash — but only when present, so
    # adding the field did not mark every published workflow as edited.
    rules: list[RuleRef] = Field(default_factory=list)

    # Read from the storage record, never persisted inside the definition —
    # the record's own columns are the source of truth.
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

    def semantic_hash(self) -> str:
        """Stable hash of the fields that affect execution.

        Deliberately excludes presentation and deployment bookkeeping
        (``ui_layout``, ``id``, ``is_deployed``, ``archived``, ``published_hash``)
        so that moving a node on the canvas does not mark a workflow dirty.
        """
        from hashlib import sha256

        payload = self.model_dump(
            mode="json",
            include={
                "name", "description", "steps",
                "entry_step", "input_schema", "variables",
            },
        )
        if self.rules:
            payload["rules"] = sorted(r.rule_id for r in self.rules)
        return sha256(
            json.dumps(payload, sort_keys=True, default=str).encode()
        ).hexdigest()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def has_unpublished_changes(self) -> bool:
        """True when the definition has moved on since the last publish.

        Exposed as a computed field so it rides along in ``model_dump()`` and
        every response model without each endpoint having to remember it.
        """
        if not self.published_hash:
            return False
        return self.published_hash != self.semantic_hash()


class StepResult(BaseModel):
    """State of a single step.

    Recorded when the step *starts* (``status="running"``) and overwritten when
    it settles, so an in-flight run exposes which step it is on rather than only
    the ones already finished.
    """
    step_id: str
    status: str                           # running | completed | failed
    output: Any = None
    error: Optional[str] = None
    duration_ms: Optional[float] = None
    started_at_ms: Optional[float] = None  # epoch ms, for live elapsed readouts
    input_preview: Optional[str] = None   # truncated query sent to agent
    output_preview: Optional[str] = None  # truncated text result


class WorkflowRun(BaseModel):
    """State of a workflow execution."""
    execution_id: str
    workflow_name: str
    status: WorkflowStatus = WorkflowStatus.PENDING
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    result: Any = None
    step_results: list[StepResult] = Field(default_factory=list)
    variables: dict = Field(default_factory=dict)


# ── Request / Response schemas ────────────────────────────────────────────

class CreateWorkflowRequest(BaseModel):
    """Request to create a new workflow."""
    definition: WorkflowDefinition


class ExecuteWorkflowRequest(BaseModel):
    """Request to execute a workflow. Follows Mistral API pattern."""
    input: dict = Field(default_factory=dict)
    wait_for_result: bool = False
    timeout_seconds: Optional[int] = None
    execution_id: Optional[str] = None


class WorkflowExecutionResponse(BaseModel):
    """Response from workflow execution — matches Mistral API pattern."""
    execution_id: str
    workflow_name: str
    status: WorkflowStatus
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    result: Any = None
    root_execution_id: Optional[str] = None
    source: Optional[str] = None  # "mistral" or "local"


class WorkflowListResponse(BaseModel):
    """List of workflows."""
    workflows: list[WorkflowDefinition]
    count: int


# ── Builder schemas ───────────────────────────────────────────────────────

class UpdateWorkflowRequest(BaseModel):
    """Draft-save an existing workflow definition from the visual builder."""
    definition: WorkflowDefinition


class ValidateWorkflowRequest(BaseModel):
    """Validate a definition without persisting it."""
    definition: WorkflowDefinition


class ValidationIssue(BaseModel):
    """A single problem found in a workflow definition."""
    severity: str            # "error" — blocks save/publish | "warning" — advisory
    code: str                # stable machine-readable identifier
    message: str
    step_id: Optional[str] = None
    field: Optional[str] = None


class ValidationResponse(BaseModel):
    """Result of validating a definition."""
    valid: bool              # False when any error-severity issue is present
    issues: list[ValidationIssue] = Field(default_factory=list)
    error_count: int = 0
    warning_count: int = 0


class ScriptResponse(BaseModel):
    """Compiled Mistral Workflows SDK source for a definition."""
    workflow_name: str
    code: str
    line_count: int
    stale: bool = False      # True when the on-disk file differs from this output


class CatalogAgent(BaseModel):
    """An agent available to drop onto the builder canvas."""
    id: str
    name: str
    model: str
    description: Optional[str] = None
    tier: Optional[str] = None
    tools: list[str] = Field(default_factory=list)
    # Connector ids attached to this agent — the canvas badges them so it is
    # obvious which agents can already reach an external service.
    connectors: list[str] = Field(default_factory=list)
    # Domain concept ids, for faceting the palette.
    domains: list[str] = Field(default_factory=list)


class CatalogTool(BaseModel):
    """A tool available to drop onto the builder canvas."""
    name: str
    description: Optional[str] = None
    parameters: dict = Field(default_factory=dict)
    required: list[str] = Field(default_factory=list)
    status: str = "approved"
    source: str = "dynamic"   # "native" | "dynamic" | "builtin"


class CatalogConnector(BaseModel):
    """A Mistral Connector available to drop onto the builder canvas."""
    id: str
    name: str
    description: Optional[str] = None
    icon_url: Optional[str] = None
    is_directory: bool = False
    is_authenticated: bool = False
    active: bool = True
    tools: list[CatalogTool] = Field(default_factory=list)


class CatalogDomain(BaseModel):
    """A domain concept, for faceting the palette."""
    id: str
    label: str
    parent_id: Optional[str] = None
    agent_count: int = 0


class DeploymentAgentSpec(BaseModel):
    """A workflow's agent, captured with enough fidelity to recreate it.

    ``tool_defs`` holds only function/builtin tool schemas (portable across
    workspaces). Connectors are workspace-bound, so they travel by name in
    ``connectors`` and are re-attached by bootstrap to the target's connector
    of that name; ``connector_ids`` keeps the source ids for reference.
    """
    source_agent_id: str
    name: str
    model: str
    description: Optional[str] = None
    instructions: str
    tier: Optional[str] = None
    tool_defs: list[dict] = Field(default_factory=list)
    connector_ids: list[str] = Field(default_factory=list)
    #: ``{"connector_name", "tool_configuration"}`` per attached connector.
    connectors: list[dict] = Field(default_factory=list)


class DeploymentDynamicTool(BaseModel):
    """A synthesized tool, with real source so it can be reproduced verbatim."""
    # Stored as ``tool_schema`` because ``schema`` shadows a BaseModel method;
    # the alias keeps the manifest's JSON key exactly as the deploy script reads it.
    model_config = ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    tool_schema: dict = Field(alias="schema")
    source_code: str
    hash: str
    version: str = "1.0.0"
    #: The version number steps pin (``tool_version``). The target keeps it on
    #: import when free, so the pinned steps resolve there too.
    version_no: Optional[int] = None
    #: "activity" — a workflow step on its own; "tool" — called by an agent.
    purpose: str = "tool"
    #: Checked against a success envelope's ``data``, as the Tool Service does.
    output_schema: Optional[dict] = None
    #: Environment variable names the code receives as ``_secrets``.
    secrets: list[str] = Field(default_factory=list)
    #: Packages beyond the standard library the code imports (pip names).
    requirements: list[str] = Field(default_factory=list)


class DeploymentConnectorRef(BaseModel):
    """A Mistral Connector the workflow depends on — a CONNECTOR step's, or an
    agent's. Bootstrap finds it on the target workspace by name, creates it
    there when it is a custom connector, stores the credentials given at
    deploy time and activates it."""
    connector_id: Optional[str] = None
    connector_name: Optional[str] = None
    credentials_name: Optional[str] = None
    #: Directory connectors are installed from Studio; they cannot be created by API.
    is_directory: bool = False
    #: The MCP server URL a custom connector is created with.
    server: Optional[str] = None
    description: Optional[str] = None
    #: "bearer" | "oauth2" | "none" — what credentials the setup form asks for.
    auth: str = "none"
    #: Where it is used, for the setup form.
    used_by: list[str] = Field(default_factory=list)
    #: The .env keys bootstrap reads this connector's credentials from.
    env_keys: dict[str, str] = Field(default_factory=dict)


class DeploymentSetupField(BaseModel):
    """One value the deploy needs from the operator, written to the server's .env."""
    key: str
    label: str
    help: str = ""
    secret: bool = False
    required: bool = False
    default: Optional[str] = None
    #: "worker" | "tool" | "connector" | "database" — groups the setup form.
    group: str = "worker"


class DeploymentManifest(BaseModel):
    """Everything needed to reproduce a workflow's execution environment
    on a different Mistral workspace: the agents it calls, the tool code
    those agents and steps depend on, and the connectors that need manual
    authorization on the target.
    """
    workflow_name: str
    description: Optional[str] = None
    agents: list[DeploymentAgentSpec] = Field(default_factory=list)
    native_tools: list[str] = Field(default_factory=list)
    dynamic_tools: list[DeploymentDynamicTool] = Field(default_factory=list)
    connectors: list[DeploymentConnectorRef] = Field(default_factory=list)
    #: An agent searches the knowledge graph: the package brings a Neo4j and a
    #: copy of these libraries' graph.
    uses_knowledge_graph: bool = False
    graph_library_ids: list[str] = Field(default_factory=list)
    #: An agent uses the SQL tools: the deploy chooses their database.
    uses_sql_tools: bool = False
    #: What the operator is asked for before the package can run.
    setup: list[DeploymentSetupField] = Field(default_factory=list)
    generated_at: str


class DeploymentSqlSetup(BaseModel):
    """Where the SQL tools' database comes from on the server."""
    #: "container" — a PostgreSQL started with the worker; "external" — ``url``.
    mode: str = "container"
    url: Optional[str] = None
    #: SQL run once into a new container database (schema and data).
    seed_sql: Optional[str] = None


class DeploymentSetup(BaseModel):
    """The operator's answers to a manifest's ``setup``, given at build time."""
    #: Written to the package's .env (download) or merged into the server's (deploy).
    env: dict[str, str] = Field(default_factory=dict)
    sql: Optional[DeploymentSqlSetup] = None


class BuilderCatalogResponse(BaseModel):
    """Everything the builder palette needs, in one round trip.

    ``tools`` and ``activities`` are disjoint: a tool attaches to an agent as
    a capability, an activity becomes a standalone step of its own. Which list
    a synthesised tool lands in is decided by its Tool Service ``purpose``.
    """
    agents: list[CatalogAgent] = Field(default_factory=list)
    tools: list[CatalogTool] = Field(default_factory=list)
    activities: list[CatalogTool] = Field(default_factory=list)
    connectors: list[CatalogConnector] = Field(default_factory=list)
    domains: list[CatalogDomain] = Field(default_factory=list)
    models: list[str] = Field(default_factory=list)
    tiers: list[str] = Field(default_factory=list)
