"""
Workflow Models — Pydantic schemas and definitions for workflow engine.
Aligned with Mistral Beta Workflows API (v1/workflows).
"""

import json
from pydantic import BaseModel, ConfigDict, Field, computed_field
from typing import Optional, Any
from datetime import datetime
from enum import Enum


class StepType(str, Enum):
    AGENT = "agent"
    TOOL = "tool"
    CONDITION = "condition"
    TRANSFORM = "transform"


class WorkflowStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TERMINATED = "TERMINATED"
    TIMED_OUT = "TIMED_OUT"
    CONTINUED_AS_NEW = "CONTINUED_AS_NEW"


class WorkflowSource(str, Enum):
    """How a workflow definition was authored."""
    PLANNER = "planner"   # generated by the LLM workflow planner
    BUILDER = "builder"   # assembled by hand in the visual builder


class NodeLayout(BaseModel):
    """Canvas coordinates for a single step in the visual builder.

    Purely presentational — the execution engine and the compiler ignore it.
    Persisted so a builder-authored graph reopens exactly as the user left it.
    """
    x: float = 0.0
    y: float = 0.0


class WorkflowStep(BaseModel):
    """A single step in the workflow DAG."""
    id: str
    type: StepType
    tier: Optional[str] = None
    config: dict = Field(default_factory=dict)
    # For agent steps: {"agent_id": "...", "query_template": "..."} or {"model": "...", "instructions": "..."}
    # For tool steps: {"tool_name": "...", "arguments_template": {}}
    # For condition steps: {"expression": "...", "true_step": "...", "false_step": "..."}
    # For transform steps: {"transform_code": "..."}
    next_steps: list[str] = Field(default_factory=list)
    description: Optional[str] = None
    parallel_group: Optional[str] = None  # Steps sharing the same group ID run concurrently via asyncio.gather()


class WorkflowDefinition(BaseModel):
    """Full workflow definition — a DAG of steps.

    This object is the single source of truth for a workflow. The compiled
    Mistral Workflows SDK module is a build artifact derived from it, never
    the other way round.
    """

    # Assignments are validated so server-side mutations (ui_layout from the
    # builder, published_hash on publish) are coerced to the declared types
    # instead of silently storing whatever shape was assigned. Definitions are
    # mutated rarely, so the per-assignment cost is irrelevant here.
    model_config = ConfigDict(validate_assignment=True)

    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    steps: list[WorkflowStep]
    entry_step: str
    input_schema: list[dict] = Field(default_factory=list)
    variables: dict = Field(default_factory=dict)
    is_deployed: bool = False
    archived: bool = False

    # ── Authoring metadata (additive; defaults keep older records loadable) ──
    source: WorkflowSource = WorkflowSource.PLANNER
    ui_layout: dict[str, NodeLayout] = Field(default_factory=dict)
    # SHA-256 of the semantic definition at the last successful publish.
    # Compared against the live hash to derive "has unpublished changes" —
    # stored rather than a boolean flag so it cannot drift out of sync.
    published_hash: Optional[str] = None

    def semantic_hash(self) -> str:
        """Stable hash of the fields that affect execution.

        Deliberately excludes presentation and deployment bookkeeping
        (``ui_layout``, ``id``, ``is_deployed``, ``archived``, ``published_hash``)
        so that moving a node on the canvas does not mark a workflow dirty.
        """
        from hashlib import sha256

        payload = self.model_dump(
            mode="json",
            include={
                "name", "description", "steps",
                "entry_step", "input_schema", "variables",
            },
        )
        return sha256(
            json.dumps(payload, sort_keys=True, default=str).encode()
        ).hexdigest()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def has_unpublished_changes(self) -> bool:
        """True when the definition has moved on since the last publish.

        Exposed as a computed field so it rides along in ``model_dump()`` and
        every response model without each endpoint having to remember it.
        """
        if not self.published_hash:
            return False
        return self.published_hash != self.semantic_hash()


class StepResult(BaseModel):
    """Result of executing a single step."""
    step_id: str
    status: str
    output: Any = None
    error: Optional[str] = None
    duration_ms: Optional[float] = None
    input_preview: Optional[str] = None   # truncated query sent to agent
    output_preview: Optional[str] = None  # truncated text result


class WorkflowRun(BaseModel):
    """State of a workflow execution."""
    execution_id: str
    workflow_name: str
    status: WorkflowStatus = WorkflowStatus.PENDING
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    result: Any = None
    step_results: list[StepResult] = Field(default_factory=list)
    variables: dict = Field(default_factory=dict)


# ── Request / Response schemas ────────────────────────────────────────────

class CreateWorkflowRequest(BaseModel):
    """Request to create a new workflow."""
    definition: WorkflowDefinition


class ExecuteWorkflowRequest(BaseModel):
    """Request to execute a workflow. Follows Mistral API pattern."""
    input: dict = Field(default_factory=dict)
    wait_for_result: bool = False
    timeout_seconds: Optional[int] = None
    execution_id: Optional[str] = None


class WorkflowExecutionResponse(BaseModel):
    """Response from workflow execution — matches Mistral API pattern."""
    execution_id: str
    workflow_name: str
    status: WorkflowStatus
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    result: Any = None
    root_execution_id: Optional[str] = None
    source: Optional[str] = None  # "mistral" or "local"


class WorkflowListResponse(BaseModel):
    """List of workflows."""
    workflows: list[WorkflowDefinition]
    count: int


# ── Builder schemas ───────────────────────────────────────────────────────

class UpdateWorkflowRequest(BaseModel):
    """Draft-save an existing workflow definition from the visual builder."""
    definition: WorkflowDefinition


class ValidateWorkflowRequest(BaseModel):
    """Validate a definition without persisting it."""
    definition: WorkflowDefinition


class ValidationIssue(BaseModel):
    """A single problem found in a workflow definition."""
    severity: str            # "error" — blocks save/publish | "warning" — advisory
    code: str                # stable machine-readable identifier
    message: str
    step_id: Optional[str] = None
    field: Optional[str] = None


class ValidationResponse(BaseModel):
    """Result of validating a definition."""
    valid: bool              # False when any error-severity issue is present
    issues: list[ValidationIssue] = Field(default_factory=list)
    error_count: int = 0
    warning_count: int = 0


class ScriptResponse(BaseModel):
    """Compiled Mistral Workflows SDK source for a definition."""
    workflow_name: str
    code: str
    line_count: int
    stale: bool = False      # True when the on-disk file differs from this output


class CatalogAgent(BaseModel):
    """An agent available to drop onto the builder canvas."""
    id: str
    name: str
    model: str
    description: Optional[str] = None
    tier: Optional[str] = None
    tools: list[str] = Field(default_factory=list)


class CatalogTool(BaseModel):
    """A tool available to drop onto the builder canvas."""
    name: str
    description: Optional[str] = None
    parameters: dict = Field(default_factory=dict)
    required: list[str] = Field(default_factory=list)
    status: str = "approved"
    source: str = "dynamic"   # "native" | "dynamic" | "builtin"


class BuilderCatalogResponse(BaseModel):
    """Everything the builder palette needs, in one round trip."""
    agents: list[CatalogAgent] = Field(default_factory=list)
    tools: list[CatalogTool] = Field(default_factory=list)
    models: list[str] = Field(default_factory=list)
    tiers: list[str] = Field(default_factory=list)
